services:
  # Backend Service
  - type: web
    name: interview-backend
    env: node
    plan: free
    buildCommand: cd server && npm ci
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromDatabase:
          name: interview-mongodb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: interview-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://interview-master-9yr2.vercel.app
      - key: LOG_LEVEL
        value: info
      - key: APP_VERSION
        value: 1.0.0
    
  # Frontend Service
  - type: web
    name: interview-frontend
    env: static
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: ./client/build
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://interview-backend.onrender.com/api/v1
      - key: REACT_APP_ENVIRONMENT
        value: production

databases:
  # MongoDB Database
  - name: interview-mongodb
    plan: free
    databaseName: interviewmaster
    user: admin

  # Redis Cache
  - name: interview-redis
    type: redis
    plan: free